name: Build and Deploy

on:
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+"]

jobs:
  build-artifact:
    name: Build
    runs-on: ubuntu-latest
    working-directory: ./packer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Packer Init
        run: packer init .

      - name: Packer Build - Tags
        if: startsWith(github.ref, 'refs/tags/v')
        run: >
          packer build
          -var "vpc_name_filter=${{ secrets.VPC_NAME_FILTER }}"
          -var "subnet_name_filter=${{ secrets.SUBNET_NAME_FILTER }}"
          -var "source_rhel_ami_name_filter=${{ secrets.AMI_NAME_FILTER }}"
          .
